---
- name: Configure target servers
  hosts: jenkins
  remote_user: root

  roles:
    - role: java
      java_packages:
        - openjdk-8-jdk
      tags:
        - java
    - { role: jenkins, tags: ['jenkins'] }
    - { role: letsencrypt, tags: ['tls', 'nginx'] }
    - { role: nginx, tags: ['nginx'] }
